[package]
name = "juggler"
version = "0.1.0"
description = "TODO juggler"
authors = ["Peter Schuller <peter.schuller@infidyne.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
