[package]
name = "juggler"
version = "0.1.0"
description = "TODO juggler"
authors = ["Peter Schuller <peter.schuller@infidyne.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0"
ratatui = "0"
color-eyre = "0"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0"
chrono = { version = "0", features = ["serde"] }
